name = "IHSetUtils"
uuid = "2fbe2ced-d81f-41b4-8f59-9b074fb3e7ff"
authors = ["defreitasL <lucas12.fp@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SciPy = "ebc72ef8-9537-4fb0-b64e-ac76025fed2d"

[compat]
SciPy = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
